# Generated by Django 4.1.5 on 2023-05-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place_tb',
            new_name='Place',
        ),
    ]
