# Generated by Django 4.1.5 on 2023-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp1', '0002_rename_place_tb_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='picture')),
                ('about', models.TextField()),
            ],
        ),
    ]
