# Generated by Django 4.1.5 on 2023-05-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp1', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
